image: maven:3.8-jdk-8

definitions:
  services:
    selenium:
      image: selenium/standalone-chrome:3.141.59

pipelines:
  default:
    - step:
        size: 2x # Double resources available for this step.
        caches:
          - maven
        services:
          - selenium
        script:
          - mvn -s settings.xml -Dxvfb.enable=false -Dwebdriver.browser="chrome:url=http://127.0.0.1:4444" -Dmaven.test.it.skip=false clean install
